## Importy


In [ ]:
import numpy as np

##Exe 8.1

In [ ]:
def test_array(array):
  print(array)
  print(array.shape)
  print(array.ndim)
  print(array.dtype)

In [ ]:
a = np.linspace(0, 1, 11, float)

test_array(a)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9 1. ]
(11,)
1
float64


In [ ]:
b = np.zeros((5, 6), dtype=int)

test_array(b)

[[0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]
 [0 0 0 0 0 0]]
(5, 6)
2
int64


In [ ]:
x = complex(0, 1)
c = x ** np.arange(9)

test_array(c)

[ 1.+0.j  0.+1.j -1.+0.j -0.-1.j  1.+0.j  0.+1.j -1.+0.j -0.-1.j  1.+0.j]
(9,)
1
complex128


## Exe 8.2

In [ ]:
v1 = np.array([9, 12, 2001, 11, 11, 2007])
print(f"v1:\n {v1}")

v2 = v1[1::2]
print(f"v2:\n {v2}")

v3 = v1[::-1]
print(f"v3:\n {v3}")

v1:
 [   9   12 2001   11   11 2007]
v2:
 [  12   11 2007]
v3:
 [2007   11   11 2001   12    9]


## Exe 8.3

In [22]:
m1 = np.random.randint(0, 100, size=(4, 5))

In [23]:
print(m1)

[[53 16 41 39 56]
 [38 29 89 55 22]
 [63 44 44 58 43]
 [94 12 29 86  5]]


In [24]:
m2 = m1[:, ::-1]

In [25]:
print(m2)

[[56 39 41 16 53]
 [22 55 89 29 38]
 [43 58 44 44 63]
 [ 5 86 29 12 94]]


In [26]:
m3 = m1[::-1, :]

In [27]:
print(m3)

[[94 12 29 86  5]
 [63 44 44 58 43]
 [38 29 89 55 22]
 [53 16 41 39 56]]


In [28]:
m4 = m1[1:-1, 1:-1]

In [29]:
print(m4)

[[29 89 55]
 [44 44 58]]
